# Name of the dbt project
name: 'oms_dbt_cloud'
version: '1.0.0'
config-version: 2

# Profile used by this project
profile: 'default'

# Project paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"


# Model configurations
models:
  oms_dbt_cloud:

    data_vault:
      +materialized: table