version: 2

sources:
  - name: sleekmart_raw
    database: SLEEKMART_OMS
    schema: RAW

    tables:
      - name: LOAD_CATEGORIES_TRADERS_SOUTH
      - name: LOAD_CATEGORIES_TRADERS_NORTH
      - name: LOAD_REGION_TRADERS_SOUTH
      - name: LOAD_REGION_TRADERS_NORTH
      - name: LOAD_SHIPPERS_TRADERS_SOUTH
      - name: LOAD_SHIPPERS_TRADERS_NORTH
      - name: LOAD_TERRITORIES_TRADERS_SOUTH
      - name: LOAD_TERRITORIES_TRADERS_NORTH
      - name: LOAD_SUPPLIERS_TRADERS_SOUTH
      - name: LOAD_SUPPLIERS_TRADERS_NORTH
      - name: LOAD_ORDER_DETAILS_TRADERS_SOUTH
      - name: LOAD_ORDERS_TRADERS_SOUTH
      - name: LOAD_PRODUCTS_TRADERS_SOUTH
      - name: LOAD_ORDER_DETAILS_TRADERS_NORTH
      - name: LOAD_ORDERS_TRADERS_NORTH
      - name: LOAD_PRODUCTS_TRADERS_NORTH
      - name: LOAD_CUSTOMERS_TRADERS_SOUTH
      - name: LOAD_CUSTOMERS_TRADERS_NORTH
      - name: LOAD_COUNTRYCODES_FILE_SOURCES

  - name: dimensional_raw
    database: DIMENSIONAL_MODELLING
    schema: RAW

    tables:
      - name: LOAD_CURRENCY_RATE
      - name: LOAD_PRODUCT
      - name: LOAD_PRODUCT_LINE
      - name: LOAD_PRODUCT_GROUP
      - name: LOAD_PRODUCT_SUB_GROUP
      - name: LOAD_PRODUCT_SALES2
      - name: LOAD_PRODUCT_LINE_SALES2
      - name: LOAD_PRODUCT_GROUP_SALES2
      - name: LOAD_PRODUCT_SUB_GROUP_SALES2