version: 2

sources:
  - name: sleekmart_raw
    database: SLEEKMART_OMS
    schema: RAW

    tables:
      - name: LOAD_CATEGORIES_TRADERS_SOUTH
      - name: LOAD_CATEGORIES_TRADERS_NORTH
      - name: LOAD_REGION_TRADERS_SOUTH
      - name: LOAD_REGION_TRADERS_NORTH
      - name: LOAD_SHIPPERS_TRADERS_SOUTH
      - name: LOAD_SHIPPERS_TRADERS_NORTH
      - name: LOAD_TERRITORIES_TRADERS_SOUTH
      - name: LOAD_TERRITORIES_TRADERS_NORTH
      - name: LOAD_SUPPLIERS_TRADERS_SOUTH
      - name: LOAD_SUPPLIERS_TRADERS_NORTH
      - name: LOAD_ORDER_DETAILS_TRADERS_SOUTH
      - name: LOAD_ORDERS_TRADERS_SOUTH
      - name: LOAD_PRODUCTS_TRADERS_SOUTH
      - name: LOAD_ORDER_DETAILS_TRADERS_NORTH
      - name: LOAD_ORDERS_TRADERS_NORTH
      - name: LOAD_PRODUCTS_TRADERS_NORTH
      - name: LOAD_CUSTOMERS_TRADERS_SOUTH
      - name: LOAD_CUSTOMERS_TRADERS_NORTH